### ISSUE TITLE
not able to install plugin for ios

### ISSUE THREAD

**Issue by vishalgole** [BlinkID/blinkid-phonegap#107]
I am working on ionic application. Below are my application details.

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.7.1

System:

    ios-deploy : 1.9.2 
    Node       : v6.13.1
    npm        : 3.10.10 
    OS         : macOS
    Xcode      : Xcode 9.4 Build version 9F1027a

While installing the plugin for ios, I got below issue..

Error: Hook failed with error code ENOENT: /Users/karthikayanmuthuramalingam/Desktop/Vishal/*****/*****/plugins/blinkid-cordova/scripts/initIOSFramework.sh

I already changed Microblink to MicroBlink as already suggested by someone...Does anyone faced same issue?

**Comment by Cerovec** [comment]
Hi @vishalgole,

Please let us know if you're still facing the same issue with the latest versions of our plugin.

Thanks!
Jurica.

**Comment by FATI6** [comment]
hello , please when i run the script $ ./initCordovaDemoApp.sh
 i face those errors : reating a new cordova project.
Adding blinkid-cordova to package.json
Using cordova-fetch for cordova-android@8
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: com.microblink.blinkid
        Name: BlinkIDDemo
        Activity: MainActivity
        Android target: android-28
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@8.1.0
Installing "blinkid-cordova" for android
Subproject Path: CordovaLib
Subproject Path: app
Plugin 'cordova-plugin-whitelist' found in config.xml... Migrating it to package.json
Discovered saved plugin "cordova-plugin-whitelist". Adding it to the project
Installing "cordova-plugin-whitelist" for android
Adding cordova-plugin-whitelist to package.json
Using cordova-fetch for cordova-ios@^5.0.0
Adding ios project...
Creating Cordova project for the iOS platform:
        Path: platforms\ios
        Package: com.microblink.blinkid
        Name: BlinkIDDemo
iOS project created with cordova-ios@5.1.1
Installing "blinkid-cordova" for ios
Running command: bash C:\Users\asus\blinkid-cordova\BlinkIDDemo\plugins\blinkid-cordova\scripts\initIOSFramework.sh C:\Users\asus\blinkid-cordova\BlinkIDDemo
ERROR: couldn't download Microblink framework, install wget
Failed to install 'blinkid-cordova': Error: Hook failed with error code 1: C:\Users\asus\blinkid-cordova\BlinkIDDemo\plugins\blinkid-cordova\scripts\initIOSFramework.sh
    at C:\Users\asus\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:224:23
    at _rejected (C:\Users\asus\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:864:24)
    at C:\Users\asus\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:890:30
    at Promise.when (C:\Users\asus\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:1142:31)
    at Promise.promise.promiseDispatch (C:\Users\asus\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:808:41)
    at C:\Users\asus\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:624:44
    at runSingle (C:\Users\asus\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:137:13)
    at flush (C:\Users\asus\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
Hook failed with error code 1: C:\Users\asus\blinkid-cordova\BlinkIDDemo\plugins\blinkid-cordova\scripts\initIOSFramework.sh
To run iOS demo application open Xcode project BlinkIDDemo.xcodeproj
To run Android demo application, position to BlinkIDDemo folder and type: cordova run android

**Comment by mparadina** [comment]
Hi @FATI6 

Just to double-check, do you have `wget` installed?

We've noticed it from the exception: `ERROR: couldn't download Microblink framework, install wget`

For Windows, you can download it here: http://gnuwin32.sourceforge.net/packages/wget.htm

Let me know if it helped.

Regards,
Milan

**Comment by eddieMicroblink** [comment]
Hi @FATI6 

Are you still experiencing the previously mentioned issues?

Regards,
Edhem
