### ISSUE TITLE
Build 5.7.1 fails to install 

### ISSUE THREAD

**Issue by AlibekJ** [BlinkID/blinkid-phonegap#134]
Tried installing blinkid-cordova and got a error.

To reproduce:

 ```
cordova create something something something
cd something
cordova platform add android
cordova plugin add blinkid-cordova
```

It fails with:
```
Using cordova-fetch for cordova-android@^8.0.0
(node:28265) Warning: Accessing non-existent property 'android' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: something
	Name: something
	Activity: MainActivity
	Android target: android-28
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@8.1.0
Installing "blinkid-cordova" for android
Error during processing of action! Attempting to revert...
Failed to install 'blinkid-cordova': Error: Uh oh!
ENOENT: no such file or directory, open '/blinkscan2/plugins/blinkid-cordova/www/blinkIdScanner.js'
    at Object.openSync (fs.js:465:3)
    at Object.readFileSync (fs.js:368:35)
    at install (/blinkscan2/platforms/android/cordova/lib/pluginHandlers.js:162:36)
    at ActionStack.process (/blinkscan2/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/blinkscan2/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/blinkscan2/node_modules/cordova-common/src/PluginManager.js:144:17)
    at /blinkscan2/platforms/android/cordova/Api.js:210:74
    at _fulfilled (/blinkscan2/node_modules/q/q.js:854:54)
    at /blinkscan2/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/blinkscan2/node_modules/q/q.js:816:13)
Uh oh!
ENOENT: no such file or directory, open '/blinkscan2/plugins/blinkid-cordova/www/blinkIdScanner.js'
```

 "blinkid-cordova": "5.7.1",
 "cordova-android": "8.1.0"

9.0.0 (cordova-lib@9.0.1)

**Version 5.7.0 works fine.**

I hope this crash report helps.

**Comment by i1E** [comment]
Hi @AlibekJ,

I cannot reproduce the issue by following steps that you have provided. For me everything works fine. Which version of the Cordova CLI you are using (`cordova --version`)? Does our [./initCordovaDemoApp.sh](https://github.com/BlinkID/blinkid-cordova/blob/master/initCordovaDemoApp.sh) work for you?

**Comment by AlibekJ** [comment]
It is 9.0.0 (cordova-lib@9.0.1)

Just tired, the same error as 3 days ago.

**Comment by i1E** [comment]
Does sample app generated with our [./initCordovaDemoApp.sh](https://github.com/BlinkID/blinkid-cordova/blob/master/initCordovaDemoApp.sh) work for you? You can replace [this](https://github.com/BlinkID/blinkid-cordova/blob/master/initCordovaDemoApp.sh#L19) line with:

```
cordova plugin add blinkid-cordova
```

to use package from the NPM.

**Comment by AlibekJ** [comment]
Nah, I just used blinkid-cordova@5.7.0 which works fine.

I can try the sample app. Let me know if it may help in debugging.

**Comment by i1E** [comment]
Hi @AlibekJ,

please try [./initCordovaDemoApp.sh](https://github.com/BlinkID/blinkid-cordova/blob/master/initCordovaDemoApp.sh) script and sample app created by this script and let us know whether it works for you or not. This will help us in debugging. 

Also, can you please send us exact steps for reproducing this issue, because we cannot reproduce the issue with steps that you have provided earlier, this worked fine:

```
cordova create something com.something something
cd something
cordova platform add android
cordova plugin add blinkid-cordova
```

**Comment by agpl** [comment]
I have exacly the same issue. I used react.cordova to initialize cordova project then moved directly to BlinkId installation which throws exactly this error.

**Comment by SandraKuzmic** [comment]
Hi @agpl 

can you send us the exact steps to reproduce the issue?

Best regards,
Sandra

**Comment by AlibekJ** [comment]
Hey @SandraKuzmic @i1E 

These are the steps literally:
```
cordova create testblink aa.blink.test testblink
cd testblink
cordova platform add android
cordova plugin add blinkid-cordova
```

**Comment by SandraKuzmic** [comment]
Hi @AlibekJ 

I still can't reproduce the error. After following your steps BlinkID plugin is successfully added to the project. 
```
$ cordova create testblink aa.blink.test testblink
Creating a new cordova project.
$ cd testblink/
$ cordova platform add android
Using cordova-fetch for cordova-android@^8.0.0
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: aa.blink.test
	Name: testblink
	Activity: MainActivity
	Android target: android-28
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@8.1.0
Plugin 'cordova-plugin-whitelist' found in config.xml... Migrating it to package.json
Discovered saved plugin "cordova-plugin-whitelist". Adding it to the project
Installing "cordova-plugin-whitelist" for android
Adding cordova-plugin-whitelist to package.json
$ cordova plugin add blinkid-cordova
Installing "blinkid-cordova" for android
Subproject Path: CordovaLib
Subproject Path: app
Adding blinkid-cordova to package.json
```

We also tried reproducing the error on different computers and none of them got the error so currently, it is hard to tell where the problem is.

We are soon to release BlinkID plugin v5.8.0 so maybe you could try it after it is released and let us know if the issue still occurs.

Best regards,
Sandra
